version: '1'
services:
  web:
    image: yamlmm
    ports:
      - "8065:8065"
    networks:
      network:
        ipv4_address: 10.5.0.5
    container_name: mattermostyaml

  database:
    image: mysql
    ports:
      - "3306:3306"
    networks:
       network:
         ipv4_address: 10.5.0.6
    container_name: sqlyaml
    volumes:
      - /home/sagar/docker/yml/data/:/var/lib/mysql

networks:
     network:
       driver: bridge
       ipam:
        config:
          - subnet: 10.5.0.0/16
            gateway: 10.5.0.1
