apiVersion: v1
kind: Service
metadata:
  name: mattermost-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
spec:
  type: LoadBalancer
  selector:
    app: mattermost-app
  ports:
    - port: 8065
      targetPort: 8065
                  