apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume6
  labels:
    type: amazonEBS
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-09716089a80dcd397
    fsType: ext4
